[package]
name = "battle_simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"

# Bevy plugins
bevy_mod_picking = "0.5"

# Other crates
dolly = "0.1.4"